package com.example.hackncsilentdisco;

import java.util.HashMap;

public class LanguageHashMap {
	/**
	 * Spanish word, English translation
	 */
	public static HashMap<String, String> map = new HashMap<>();

	static {
		map.put("el, la", "the");
		map.put("de", "of, from");
		map.put("que", "that, which");
		map.put("y", "and");
		map.put("a", "to, at");
		map.put("en", "in, on");
		map.put("un", "a, an");
		map.put("ser", "to be (norm)");
		map.put("se", "[reflexive marker]");
		map.put("no", "no");
		map.put("haber", "to have (+Ved)");
		map.put("por", "by, for, through");
		map.put("con", "with");
		map.put("su", "his/her/their/your (-fam)");
		map.put("para", "for, to, in order to");
		map.put("como", "like, as");
		map.put("estar", "to be (location, change from norm)");
		map.put("tener", "to have");
		map.put("le", "[3rd person] (indirect obj)");
		map.put("lo", "the (+ neuter)");
		map.put("lo", "[3rd person] (direct obj-m)");
		map.put("todo", "all, every");
		map.put("pero", "but, yet, except");
		map.put("más", "more");
		map.put("hacer", "to do, make");
		map.put("o", "or");
		map.put("poder", "to be able to; can");
		map.put("decir", "to tell, say");
		map.put("este", "this (m) [esta (f)]");
		map.put("ir", "to go");
		map.put("otro", "other, another");
		map.put("ese", "that (m) [esa (f)]");
		map.put("la", "[3rd person] (direct obj-f)");
		map.put("si", "if, whether");
		map.put("me", "me (obj)");
		map.put("ya", "already, still");
		map.put("ver", "to see");
		map.put("porque", "because");
		map.put("dar", "to give");
		map.put("cuándo", "when");
		map.put("él", "he, [ellos] them (m)");
		map.put("muy", "very, really");
		map.put("sin", "without");
		map.put("vez", "time (specific occurrence)");
		map.put("mucho", "much, many, a lot (adv)");
		map.put("saber", "to know (a fact), find out");
		map.put("qué", "what?, which?, how (+ adj)!");
		map.put("sobre", "on top of, over, about");
		map.put("mi", "my");
		map.put("alguno", "some, someone (pron)");
		map.put("mismo", "same");
		map.put("yo", "I (subj)");
		map.put("también", "also");
		map.put("hasta", "until, up to, even (adv)");
		map.put("año", "year");
		map.put("dos", "two");
		map.put("querer", "to want, love");
		map.put("entre", "between, among");
		map.put("así", "like that");
		map.put("primero", "first");
		map.put("desde", "from, since");
		map.put("grande", "large, great, big");
		map.put("eso", "that (n)");
		map.put("ni", "not even, neither, nor");
		map.put("nos", "us (obj)");
		map.put("llegar", "to arrive");
		map.put("pasar", "to pass, spend (time)");
		map.put("tiempo", "time (general), weather");
		map.put("ella", "she, [ellas] them (f)");
		map.put("sí", "yes");
		map.put("día", "day");
		map.put("uno", "one");
		map.put("bien", "well");
		map.put("poco", "little, few, a little bit (adv)");
		map.put("deber", "should, ought to; to owe");
		map.put("entonces", "so, then");
		map.put("poner", "to put (on), get (+adj)");
		map.put("cosa", "thing");
		map.put("tanto", "so much, so many");
		map.put("hombre", "man, mankind, husband");
		map.put("parecer", "to seem, look like");
		map.put("nuestro", "our");
		map.put("tan", "such, as, too, so");
		map.put("dónde", "where");
		map.put("ahora", "now");
		map.put("parte", "part, portion");
		map.put("después", "after");
		map.put("vida", "life");
		map.put("quedar", "to remain, stay");
		map.put("siempre", "always, forever");
		map.put("creer", "to believe, think");
		map.put("hablar", "to speak, talk");
		map.put("llevar", "to take, carry");
		map.put("dejar", "to let, leave");
		map.put("nada", "nothing, (not) at all");
		map.put("cada", "each, every");
		map.put("seguir", "to follow, keep on");
		map.put("menos", "less, fewer");
		map.put("nuevo", "new");
		map.put("encontrar", "to find");
	}
}
